# 公共配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
zk:
  url: zookeeper://10.1.58.225:2181
dubbo:
  registry:
    address: ${zk.url}
host:
  list: fe80::20d1:121d:a586:7903,fe80::2fd3:9937:453d:72b5,10.1.58.219,fe80::8804:28d2:da0e:67d9,fe80::971f:2776:5a6e:dc5,10.1.58.220,fe80::ca14:84a7:5b8a:6ae5,10.1.58.226,fe80::b1f3:6065:e6dd:c947,10.1.58.225,10.1.58.236,10.1.58.224,10.1.58.235,127.0.0.1,10.1.58.234

uyun:
  baseurl: http://10.1.58.224/
  apikey: efc54475ce7f11ebbf2a005056b93ac1

whale:
  distributed:
    config:
      bootstrap:
        enabled: false

forest:
  variables:
    baseUrl: ${uyun.baseurl}
    apikey: ${uyun.apikey}


